create extension if not exists pgcrypto;

create table if not exists public.sf_inventory (
  id bigint generated by default as identity primary key,
  source_row integer unique,
  type text not null default '', sku text not null default '', brand text not null default '', item_name text not null,
  quantity numeric not null default 0 check (quantity >= 0), uom text not null default 'unit', location text not null default 'Outlet',
  expiry_date text not null default '', received_date text not null default '', remarks text not null default '', weight numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.sf_purchase_requests (
  id uuid primary key default gen_random_uuid(), pr_id text not null unique, requested_at timestamptz not null default now(),
  requested_by text not null, department text not null, location text not null default 'Outlet', email text not null default '',
  status text not null default 'Submitted' check (status in ('Submitted','Reviewed','Approved','Rejected','Ordered','Partially Received','Received','Cancelled')),
  designated_reviewer text not null, reviewed_by text, reviewed_at timestamptz, review_note text not null default '',
  approved_by text, approved_at timestamptz, approval_note text not null default '', items jsonb not null default '[]'::jsonb,
  remarks text not null default '', legacy_row integer, updated_at timestamptz not null default now()
);

create table if not exists public.sf_usage_transactions (
  id bigint generated by default as identity primary key, inventory_id bigint references public.sf_inventory(id), employee text not null,
  department text not null, location text not null, quantity numeric not null check (quantity > 0), uom text not null,
  reason text not null default 'Used', remarks text not null default '', created_at timestamptz not null default now()
);

create table if not exists public.sf_receipts (
  id bigint generated by default as identity primary key, purchase_request_id uuid references public.sf_purchase_requests(id) on delete cascade,
  pr_id text not null, item_key text not null, item_name text not null, receiver text not null, location text not null,
  quantity numeric not null check (quantity > 0), uom text not null, expiry_date text not null default '', package_photo_path text,
  invoice_photo_path text, remarks text not null default '', created_at timestamptz not null default now()
);

create table if not exists public.sf_daily_operations (
  id bigint generated by default as identity primary key, employee text not null, department text not null, location text not null,
  shift text not null, checks jsonb not null default '[]'::jsonb, issues text not null default '', created_at timestamptz not null default now()
);

create table if not exists public.sf_audit_log (
  id bigint generated by default as identity primary key, actor text not null, action text not null, entity_type text not null,
  entity_id text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

alter table public.sf_inventory enable row level security;
alter table public.sf_purchase_requests enable row level security;
alter table public.sf_usage_transactions enable row level security;
alter table public.sf_receipts enable row level security;
alter table public.sf_daily_operations enable row level security;
alter table public.sf_audit_log enable row level security;
revoke all on public.sf_inventory, public.sf_purchase_requests, public.sf_usage_transactions, public.sf_receipts, public.sf_daily_operations, public.sf_audit_log from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('senza-fine-receipts','senza-fine-receipts',false,5242880,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do update set public=false, file_size_limit=5242880, allowed_mime_types=excluded.allowed_mime_types;
